In [1]:
import pandas as pd
import numpy as np

sheet_id = "1_NNEqQl9CPxbRMTbxwkvemA8_xJ8ERsIK8x0rZBBD90"
gid = "911197866"
url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=csv&gid={gid}"
df = pd.read_csv(url, skiprows=9)
df.to_csv("sysarmy_encuesta_2025_limpia.csv", index=False)

In [2]:
df.columns = df.columns.str.lower().str.replace(' ', '_')

In [3]:
categorical_columns = list(df.dtypes[df.dtypes == 'object'].index)

for c in categorical_columns:
    df[c] = df[c].str.lower().str.replace(' ', '_')

In [4]:
df.dtypes

donde_estas_trabajando                                                                            object
dedicacion                                                                                        object
tipo_de_contrato                                                                                  object
ultimo_salario_mensual_o_retiro_bruto_en_pesos_argentinos                                        float64
ultimo_salario_mensual_o_retiro_neto_en_pesos_argentinos                                         float64
pagos_en_dolares                                                                                  object
si_tu_sueldo_esta_dolarizado_cual_fue_el_ultimo_valor_del_dolar_que_tomaron                       object
recibis_algun_tipo_de_bono                                                                        object
a_que_esta_atado_el_bono                                                                          object
tuviste_actualizaciones_de_tus_ingresos_laborales_durante_el_ultimo_semestre                      object
de_que_fue_el_ajuste_total_acumulado                                                             float64
en_que_mes_fue_el_ultimo_ajuste                                                                   object
como_consideras_que_estan_tus_ingresos_laborales_comparados_con_el_semestre_anterior               int64
contas_con_beneficios_adicionales                                                                 object
que_tan_conforme_estas_con_tus_ingresos_laborales                                                  int64
estas_buscando_trabajo                                                                            object
pluriempleo                                                                                       object
trabajo_de                                                                                        object
anos_de_experiencia                                                                                int64
antiguedad_en_la_empresa_actual                                                                    int64
anos_en_el_puesto_actual                                                                           int64
cuantas_personas_tenes_a_cargo                                                                     int64
plataformas_que_utilizas_en_tu_puesto_actual                                                      object
lenguajes_de_programacion_o_tecnologias_que_utilices_en_tu_puesto_actual                          object
frameworksherramientas_y_librerias_que_utilices_en_tu_puesto_actual                               object
bases_de_datos                                                                                    object
qa_testing                                                                                        object
cantidad_de_personas_en_tu_organizacion                                                           object
modalidad_de_trabajo                                                                              object
si_trabajas_bajo_un_esquema_hibrido_cuantos_dias_a_la_semana_vas_a_la_oficina                      int64
en_los_ultimos_6_mesesse_aplico_alguna_politica_de_ajustes_salariales                             object
en_los_ultimos_6_meseshubo_reduccion_de_personal                                                  object
la_recomendas_como_un_buen_lugar_para_trabajar                                                     int64
que_tanto_estas_usando_copilotchatgpt_u_otras_herramientas_de_ia_para_tu_trabajo                   int64
vibe_coding                                                                                       object
salir_o_seguir_contestando                                                                        object
maximo_nivel_de_estudios                                                                          object
estado                                                                                            object
carrera                                                                                           object
institucion_educativa                                                                             object
salir_o_seguir_contestando_sobre_las_guardias                                                     object
cual_es_la_cantidad_maxima_de_entrevistas_que_consideras_aceptable_en_un_proceso_de_seleccion     object
cual_es_la_combinacion_de_entrevistas_que_consideras_mejor_en_tu_experiencia_como_candidatoa      object
desafios_tecnicoscomo_los_preferiselegi_todas_las_opciones_que_consideres                         object
cuantas_horas_te_parecen_correctas_dedicarle_a_un_desafio_tecnico_asincronico                     object
cual_de_las_siguientes_frases_representa_mejor_tu_opinion_acerca_de_los_procesos_de_seleccion     object
salir_o_seguir_contestando_sobre_las_guardias1                                                    object
tenes_guardias                                                                                    object
cuanto_cobras_por_guardia                                                                        float64
aclara_el_numero_que_ingresaste_en_el_campo_anterior                                              object
tengo_edad                                                                                         int64
genero                                                                                            object
habias_respondido_nuestra_encuesta_en_ediciones_anteriores                                        object
sueldo_dolarizado                                                                                   bool
seniority                                                                                         object
_sal                                                                                             float64
dtype: object

In [5]:
categorias=['donde_estas_trabajando','dedicacion','pagos_en_dolares','recibis_algun_tipo_de_bono','tuviste_actualizaciones_de_tus_ingresos_laborales_durante_el_ultimo_semestre','contas_con_beneficios_adicionales',
'estas_buscando_trabajo',
'pluriempleo',
'trabajo_de',
'anos_de_experiencia',
'antiguedad_en_la_empresa_actual',
'anos_en_el_puesto_actual', 
'cuantas_personas_tenes_a_cargo',
'cantidad_de_personas_en_tu_organizacion',
'modalidad_de_trabajo',
'maximo_nivel_de_estudios',
'estado',
'tenes_guardias',
'cuanto_cobras_por_guardia',
'aclara_el_numero_que_ingresaste_en_el_campo_anterior',
'tengo_edad',
'genero',
'sueldo_dolarizado',
'seniority',
'_sal']

In [9]:
df=df[categorias]

In [7]:
df

,donde_estas_trabajando,dedicacion,tipo_de_contrato,ultimo_salario_mensual_o_retiro_bruto_en_pesos_argentinos,ultimo_salario_mensual_o_retiro_neto_en_pesos_argentinos,pagos_en_dolares,si_tu_sueldo_esta_dolarizado_cual_fue_el_ultimo_valor_del_dolar_que_tomaron,recibis_algun_tipo_de_bono,a_que_esta_atado_el_bono,tuviste_actualizaciones_de_tus_ingresos_laborales_durante_el_ultimo_semestre,...,salir_o_seguir_contestando_sobre_las_guardias1,tenes_guardias,cuanto_cobras_por_guardia,aclara_el_numero_que_ingresaste_en_el_campo_anterior,tengo_edad,genero,habias_respondido_nuestra_encuesta_en_ediciones_anteriores,sueldo_dolarizado,seniority,_sal
0,ciudad_autónoma_de_buenos_aires,full-time,staff_(planta_permanente),2511178.00,2085000.00,cobro_parte_del_salario_en_dólares,dólar_oficial_al_día_de_oago,no,no_recibo_bono,uno,...,NaN,NaN,NaN,NaN,43,mujer_cis,no,True,semi-senior,2511178.00
1,buenos_aires,full-time,tercerizado_(trabajo_a_través_de_consultora_o_...,2140000.00,2140000.00,cobro_todo_el_salario_en_dólares,1160,no,no_recibo_bono,uno,...,NaN,NaN,NaN,NaN,59,mujer_cis,sí,True,senior,2140000.00
2,ciudad_autónoma_de_buenos_aires,full-time,staff_(planta_permanente),3000000.00,310000.00,cobro_parte_del_salario_en_dólares,NaN,3+_sueldos,performance_de_la_compañía,no,...,NaN,NaN,NaN,NaN,39,hombre_cis,sí,True,semi-senior,3000000.00
3,mendoza,full-time,contractor,4000000.00,4000000.00,cobro_todo_el_salario_en_dólares,1185,no,no_recibo_bono,no,...,terminar_encuesta,no,0.0,neto,37,hombre_cis,sí,True,senior,4000000.00
4,buenos_aires,full-time,staff_(planta_permanente),1300000.00,1000000.00,cobro_parte_del_salario_en_dólares,NaN,de_uno_a_tres_sueldos,mix_de_las_anteriores,no,...,NaN,NaN,NaN,NaN,35,hombre_cis,sí,True,senior,1300000.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3743,buenos_aires,part-time,staff_(planta_permanente),4500000.00,4250000.00,NaN,NaN,un_sueldo,performance_individual,uno,...,NaN,NaN,NaN,NaN,27,hombre_cis,no,False,senior,4500000.00
3744,buenos_aires,full-time,tercerizado_(trabajo_a_través_de_consultora_o_...,1400000.00,1200000.00,NaN,NaN,no,no_recibo_bono,uno,...,NaN,NaN,NaN,NaN,25,hombre_cis,sí,False,semi-senior,1400000.00
3745,ciudad_autónoma_de_buenos_aires,full-time,staff_(planta_permanente),3700000.00,3200000.00,NaN,NaN,no,no_recibo_bono,dos,...,NaN,NaN,NaN,NaN,43,hombre_cis,sí,False,senior,3700000.00
3746,ciudad_autónoma_de_buenos_aires,full-time,staff_(planta_permanente),3200000.00,2567000.00,NaN,NaN,un_sueldo,mix_de_las_anteriores,tres,...,NaN,NaN,NaN,NaN,24,hombre_cis,sí,False,semi-senior,3200000.00
3747,santa_fe,full-time,participación_societaria_en_una_cooperativa,1310771.18,1117423.86,NaN,NaN,de_uno_a_tres_sueldos,votado_por_decisión_colectiva,uno,...,terminar_encuesta,NaN,NaN,NaN,33,hombre_cis,no,False,semi-senior,1310771.18

In [8]:
df._sal=pd.to_numeric(df._sal, errors='coerce')

In [9]:

# Suponiendo que tu dataframe se llama df
# 1. Rellenar con 0 el monto del bono para los que no reciben
df.cuanto_cobras_por_guardia = df.cuanto_cobras_por_guardia.fillna(0)

In [11]:
nulos_totales = df.isna().sum()
print(nulos_totales)

donde_estas_trabajando                                                                              0
dedicacion                                                                                          0
tipo_de_contrato                                                                                    0
ultimo_salario_mensual_o_retiro_bruto_en_pesos_argentinos                                           0
ultimo_salario_mensual_o_retiro_neto_en_pesos_argentinos                                          168
pagos_en_dolares                                                                                 2478
si_tu_sueldo_esta_dolarizado_cual_fue_el_ultimo_valor_del_dolar_que_tomaron                      2939
recibis_algun_tipo_de_bono                                                                          0
a_que_esta_atado_el_bono                                                                            0
tuviste_actualizaciones_de_tus_ingresos_laborales_durante_el_ultimo_semestre                        0
de_que_fue_el_ajuste_total_acumulado                                                                0
en_que_mes_fue_el_ultimo_ajuste                                                                     0
como_consideras_que_estan_tus_ingresos_laborales_comparados_con_el_semestre_anterior                0
contas_con_beneficios_adicionales                                                                   0
que_tan_conforme_estas_con_tus_ingresos_laborales                                                   0
estas_buscando_trabajo                                                                              0
pluriempleo                                                                                      3516
trabajo_de                                                                                          0
anos_de_experiencia                                                                                 0
antiguedad_en_la_empresa_actual                                                                     0
anos_en_el_puesto_actual                                                                            0
cuantas_personas_tenes_a_cargo                                                                      0
plataformas_que_utilizas_en_tu_puesto_actual                                                        0
lenguajes_de_programacion_o_tecnologias_que_utilices_en_tu_puesto_actual                            1
frameworksherramientas_y_librerias_que_utilices_en_tu_puesto_actual                                 2
bases_de_datos                                                                                      1
qa_testing                                                                                          3
cantidad_de_personas_en_tu_organizacion                                                             0
modalidad_de_trabajo                                                                                0
si_trabajas_bajo_un_esquema_hibrido_cuantos_dias_a_la_semana_vas_a_la_oficina                       0
en_los_ultimos_6_mesesse_aplico_alguna_politica_de_ajustes_salariales                            1626
en_los_ultimos_6_meseshubo_reduccion_de_personal                                                    0
la_recomendas_como_un_buen_lugar_para_trabajar                                                      0
que_tanto_estas_usando_copilotchatgpt_u_otras_herramientas_de_ia_para_tu_trabajo                    0
vibe_coding                                                                                         0
salir_o_seguir_contestando                                                                          0
maximo_nivel_de_estudios                                                                         2224
estado                                                                                           2224
carrera                                                                                          2264
institucion_educativa                                                                            2539
salir_o_seguir_contestando_sobre_las_guardias                                                    2224
cual_es_la_cantidad_maxima_de_entrevistas_que_consideras_aceptable_en_un_proceso_de_seleccion    2578
cual_es_la_combinacion_de_entrevistas_que_consideras_mejor_en_tu_experiencia_como_candidatoa     2579
desafios_tecnicoscomo_los_preferiselegi_todas_las_opciones_que_consideres                        2607
cuantas_horas_te_parecen_correctas_dedicarle_a_un_desafio_tecnico_asincronico                    2600
cual_de_las_siguientes_frases_representa_mejor_tu_opinion_acerca_de_los_procesos_de_seleccion    2599
salir_o_seguir_contestando_sobre_las_guardias1                                                   2578
tenes_guardias                                                                                   2788
cuanto_cobras_por_guardia                                                                           0
aclara_el_numero_que_ingresaste_en_el_campo_anterior                                             2788
tengo_edad                                                                                          0
genero                                                                                              0
habias_respondido_nuestra_encuesta_en_ediciones_anteriores                                          0
sueldo_dolarizado                                                                                   0
seniority                                                                                           0
_sal                                                                                                0
dtype: int64

In [12]:
df = df.drop(columns=['estado','pluriempleo','pagos_en_dolares','maximo_nivel_de_estudios','aclara_el_numero_que_ingresaste_en_el_campo_anterior','tenes_guardias','cuanto_cobras_por_guardia'])

In [13]:
df

,donde_estas_trabajando,dedicacion,tipo_de_contrato,ultimo_salario_mensual_o_retiro_bruto_en_pesos_argentinos,ultimo_salario_mensual_o_retiro_neto_en_pesos_argentinos,si_tu_sueldo_esta_dolarizado_cual_fue_el_ultimo_valor_del_dolar_que_tomaron,recibis_algun_tipo_de_bono,a_que_esta_atado_el_bono,tuviste_actualizaciones_de_tus_ingresos_laborales_durante_el_ultimo_semestre,de_que_fue_el_ajuste_total_acumulado,...,desafios_tecnicoscomo_los_preferiselegi_todas_las_opciones_que_consideres,cuantas_horas_te_parecen_correctas_dedicarle_a_un_desafio_tecnico_asincronico,cual_de_las_siguientes_frases_representa_mejor_tu_opinion_acerca_de_los_procesos_de_seleccion,salir_o_seguir_contestando_sobre_las_guardias1,tengo_edad,genero,habias_respondido_nuestra_encuesta_en_ediciones_anteriores,sueldo_dolarizado,seniority,_sal
0,ciudad_autónoma_de_buenos_aires,full-time,staff_(planta_permanente),2511178.00,2085000.00,dólar_oficial_al_día_de_oago,no,no_recibo_bono,uno,9.0,...,NaN,NaN,NaN,NaN,43,mujer_cis,no,True,semi-senior,2511178.00
1,buenos_aires,full-time,tercerizado_(trabajo_a_través_de_consultora_o_...,2140000.00,2140000.00,1160,no,no_recibo_bono,uno,5.0,...,NaN,NaN,NaN,NaN,59,mujer_cis,sí,True,senior,2140000.00
2,ciudad_autónoma_de_buenos_aires,full-time,staff_(planta_permanente),3000000.00,310000.00,NaN,3+_sueldos,performance_de_la_compañía,no,0.0,...,NaN,NaN,NaN,NaN,39,hombre_cis,sí,True,semi-senior,3000000.00
3,mendoza,full-time,contractor,4000000.00,4000000.00,1185,no,no_recibo_bono,no,0.0,...,"asincrónicos,_y_sin_plataformas._ejercicios_de...","más_de_8_horas,_sin_problemas","aunque_me_interese,_no_quiero_invertir_mucho_t...",terminar_encuesta,37,hombre_cis,sí,True,senior,4000000.00
4,buenos_aires,full-time,staff_(planta_permanente),1300000.00,1000000.00,NaN,de_uno_a_tres_sueldos,mix_de_las_anteriores,no,0.0,...,NaN,NaN,NaN,NaN,35,hombre_cis,sí,True,senior,1300000.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3743,buenos_aires,part-time,staff_(planta_permanente),4500000.00,4250000.00,NaN,un_sueldo,performance_individual,uno,5.0,...,NaN,NaN,NaN,NaN,27,hombre_cis,no,False,senior,4500000.00
3744,buenos_aires,full-time,tercerizado_(trabajo_a_través_de_consultora_o_...,1400000.00,1200000.00,NaN,no,no_recibo_bono,uno,5.0,...,NaN,NaN,NaN,NaN,25,hombre_cis,sí,False,semi-senior,1400000.00
3745,ciudad_autónoma_de_buenos_aires,full-time,staff_(planta_permanente),3700000.00,3200000.00,NaN,no,no_recibo_bono,dos,16.0,...,NaN,NaN,NaN,NaN,43,hombre_cis,sí,False,senior,3700000.00
3746,ciudad_autónoma_de_buenos_aires,full-time,staff_(planta_permanente),3200000.00,2567000.00,NaN,un_sueldo,mix_de_las_anteriores,tres,25.0,...,NaN,NaN,NaN,NaN,24,hombre_cis,sí,False,semi-senior,3200000.00
3747,santa_fe,full-time,participación_societaria_en_una_cooperativa,1310771.18,1117423.86,NaN,de_uno_a_tres_sueldos,votado_por_decisión_colectiva,uno,21.0,...,"asincrónicos,_y_sin_plataformas._ejercicios_de...",hasta_2_horas,"si_me_interesa_la_empresa,_invierto_todo_el_ti...",terminar_encuesta,33,hombre_cis,no,False,semi-senior,1310771.18

In [14]:
df.sueldo_dolarizado = df.sueldo_dolarizado.astype(int)

In [15]:
df

,donde_estas_trabajando,dedicacion,tipo_de_contrato,ultimo_salario_mensual_o_retiro_bruto_en_pesos_argentinos,ultimo_salario_mensual_o_retiro_neto_en_pesos_argentinos,si_tu_sueldo_esta_dolarizado_cual_fue_el_ultimo_valor_del_dolar_que_tomaron,recibis_algun_tipo_de_bono,a_que_esta_atado_el_bono,tuviste_actualizaciones_de_tus_ingresos_laborales_durante_el_ultimo_semestre,de_que_fue_el_ajuste_total_acumulado,...,desafios_tecnicoscomo_los_preferiselegi_todas_las_opciones_que_consideres,cuantas_horas_te_parecen_correctas_dedicarle_a_un_desafio_tecnico_asincronico,cual_de_las_siguientes_frases_representa_mejor_tu_opinion_acerca_de_los_procesos_de_seleccion,salir_o_seguir_contestando_sobre_las_guardias1,tengo_edad,genero,habias_respondido_nuestra_encuesta_en_ediciones_anteriores,sueldo_dolarizado,seniority,_sal
0,ciudad_autónoma_de_buenos_aires,full-time,staff_(planta_permanente),2511178.00,2085000.00,dólar_oficial_al_día_de_oago,no,no_recibo_bono,uno,9.0,...,NaN,NaN,NaN,NaN,43,mujer_cis,no,1,semi-senior,2511178.00
1,buenos_aires,full-time,tercerizado_(trabajo_a_través_de_consultora_o_...,2140000.00,2140000.00,1160,no,no_recibo_bono,uno,5.0,...,NaN,NaN,NaN,NaN,59,mujer_cis,sí,1,senior,2140000.00
2,ciudad_autónoma_de_buenos_aires,full-time,staff_(planta_permanente),3000000.00,310000.00,NaN,3+_sueldos,performance_de_la_compañía,no,0.0,...,NaN,NaN,NaN,NaN,39,hombre_cis,sí,1,semi-senior,3000000.00
3,mendoza,full-time,contractor,4000000.00,4000000.00,1185,no,no_recibo_bono,no,0.0,...,"asincrónicos,_y_sin_plataformas._ejercicios_de...","más_de_8_horas,_sin_problemas","aunque_me_interese,_no_quiero_invertir_mucho_t...",terminar_encuesta,37,hombre_cis,sí,1,senior,4000000.00
4,buenos_aires,full-time,staff_(planta_permanente),1300000.00,1000000.00,NaN,de_uno_a_tres_sueldos,mix_de_las_anteriores,no,0.0,...,NaN,NaN,NaN,NaN,35,hombre_cis,sí,1,senior,1300000.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3743,buenos_aires,part-time,staff_(planta_permanente),4500000.00,4250000.00,NaN,un_sueldo,performance_individual,uno,5.0,...,NaN,NaN,NaN,NaN,27,hombre_cis,no,0,senior,4500000.00
3744,buenos_aires,full-time,tercerizado_(trabajo_a_través_de_consultora_o_...,1400000.00,1200000.00,NaN,no,no_recibo_bono,uno,5.0,...,NaN,NaN,NaN,NaN,25,hombre_cis,sí,0,semi-senior,1400000.00
3745,ciudad_autónoma_de_buenos_aires,full-time,staff_(planta_permanente),3700000.00,3200000.00,NaN,no,no_recibo_bono,dos,16.0,...,NaN,NaN,NaN,NaN,43,hombre_cis,sí,0,senior,3700000.00
3746,ciudad_autónoma_de_buenos_aires,full-time,staff_(planta_permanente),3200000.00,2567000.00,NaN,un_sueldo,mix_de_las_anteriores,tres,25.0,...,NaN,NaN,NaN,NaN,24,hombre_cis,sí,0,semi-senior,3200000.00
3747,santa_fe,full-time,participación_societaria_en_una_cooperativa,1310771.18,1117423.86,NaN,de_uno_a_tres_sueldos,votado_por_decisión_colectiva,uno,21.0,...,"asincrónicos,_y_sin_plataformas._ejercicios_de...",hasta_2_horas,"si_me_interesa_la_empresa,_invierto_todo_el_ti...",terminar_encuesta,33,hombre_cis,no,0,semi-senior,1310771.18

In [16]:
df.nunique()

donde_estas_trabajando                                                                             24
dedicacion                                                                                          2
tipo_de_contrato                                                                                    5
ultimo_salario_mensual_o_retiro_bruto_en_pesos_argentinos                                        1542
ultimo_salario_mensual_o_retiro_neto_en_pesos_argentinos                                         1463
si_tu_sueldo_esta_dolarizado_cual_fue_el_ultimo_valor_del_dolar_que_tomaron                       216
recibis_algun_tipo_de_bono                                                                          5
a_que_esta_atado_el_bono                                                                          111
tuviste_actualizaciones_de_tus_ingresos_laborales_durante_el_ultimo_semestre                        5
de_que_fue_el_ajuste_total_acumulado                                                              201
en_que_mes_fue_el_ultimo_ajuste                                                                     8
como_consideras_que_estan_tus_ingresos_laborales_comparados_con_el_semestre_anterior                4
contas_con_beneficios_adicionales                                                                1451
que_tan_conforme_estas_con_tus_ingresos_laborales                                                   4
estas_buscando_trabajo                                                                              3
trabajo_de                                                                                         58
anos_de_experiencia                                                                                43
antiguedad_en_la_empresa_actual                                                                    35
anos_en_el_puesto_actual                                                                           29
cuantas_personas_tenes_a_cargo                                                                     44
plataformas_que_utilizas_en_tu_puesto_actual                                                      968
lenguajes_de_programacion_o_tecnologias_que_utilices_en_tu_puesto_actual                         1059
frameworksherramientas_y_librerias_que_utilices_en_tu_puesto_actual                               929
bases_de_datos                                                                                    859
qa_testing                                                                                        428
cantidad_de_personas_en_tu_organizacion                                                            11
modalidad_de_trabajo                                                                                3
si_trabajas_bajo_un_esquema_hibrido_cuantos_dias_a_la_semana_vas_a_la_oficina                       6
en_los_ultimos_6_mesesse_aplico_alguna_politica_de_ajustes_salariales                            1147
en_los_ultimos_6_meseshubo_reduccion_de_personal                                                    3
la_recomendas_como_un_buen_lugar_para_trabajar                                                     11
que_tanto_estas_usando_copilotchatgpt_u_otras_herramientas_de_ia_para_tu_trabajo                    6
vibe_coding                                                                                         3
salir_o_seguir_contestando                                                                          4
carrera                                                                                           124
institucion_educativa                                                                              46
salir_o_seguir_contestando_sobre_las_guardias                                                       3
cual_es_la_cantidad_maxima_de_entrevistas_que_consideras_aceptable_en_un_proceso_de_seleccion       4
cual_es_la_combinacion_de_entrevistas_que_consideras_mejor_en_tu_experiencia_como_candidatoa       55
desafios_tecnicoscomo_los_preferiselegi_todas_las_opciones_que_consideres                          43
cuantas_horas_te_parecen_correctas_dedicarle_a_un_desafio_tecnico_asincronico                       6
cual_de_las_siguientes_frases_representa_mejor_tu_opinion_acerca_de_los_procesos_de_seleccion       4
salir_o_seguir_contestando_sobre_las_guardias1                                                      3
tengo_edad                                                                                         54
genero                                                                                              8
habias_respondido_nuestra_encuesta_en_ediciones_anteriores                                          2
sueldo_dolarizado                                                                                   2
seniority                                                                                           3
_sal                                                                                             1542
dtype: int64

In [17]:
# Supongamos que tu columna se llama 'puesto'
# 1. Vemos cuáles son los 5 puestos más comunes
top_5_puestos = df['contas_con_beneficios_adicionales'].value_counts().nlargest(3).index

In [18]:
top_5_puestos

Index(['ninguna_de_las_anteriores', 'horarios_flexibles',
       'horarios_flexibles,_vacaciones_flexibles_(adicionales_a_las_reglamentarias)'],
      dtype='object', name='contas_con_beneficios_adicionales')

In [19]:
# Reemplaza 'tu_columna' por el nombre real de tu columna
conteo_top_5 = df['contas_con_beneficios_adicionales'].value_counts().head(5)

print(conteo_top_5)

contas_con_beneficios_adicionales
ninguna_de_las_anteriores                                                      534
horarios_flexibles                                                             184
horarios_flexibles,_vacaciones_flexibles_(adicionales_a_las_reglamentarias)     99
abono_de_internet                                                               75
capacitaciones_y/o_cursos                                                       55
Name: count, dtype: int64

In [20]:
df['contas_con_beneficios_adicionales'] = df['contas_con_beneficios_adicionales'].where(df['contas_con_beneficios_adicionales'].isin(top_5_puestos), 'Otros')

In [21]:
df

,donde_estas_trabajando,dedicacion,tipo_de_contrato,ultimo_salario_mensual_o_retiro_bruto_en_pesos_argentinos,ultimo_salario_mensual_o_retiro_neto_en_pesos_argentinos,si_tu_sueldo_esta_dolarizado_cual_fue_el_ultimo_valor_del_dolar_que_tomaron,recibis_algun_tipo_de_bono,a_que_esta_atado_el_bono,tuviste_actualizaciones_de_tus_ingresos_laborales_durante_el_ultimo_semestre,de_que_fue_el_ajuste_total_acumulado,...,desafios_tecnicoscomo_los_preferiselegi_todas_las_opciones_que_consideres,cuantas_horas_te_parecen_correctas_dedicarle_a_un_desafio_tecnico_asincronico,cual_de_las_siguientes_frases_representa_mejor_tu_opinion_acerca_de_los_procesos_de_seleccion,salir_o_seguir_contestando_sobre_las_guardias1,tengo_edad,genero,habias_respondido_nuestra_encuesta_en_ediciones_anteriores,sueldo_dolarizado,seniority,_sal
0,ciudad_autónoma_de_buenos_aires,full-time,staff_(planta_permanente),2511178.00,2085000.00,dólar_oficial_al_día_de_oago,no,no_recibo_bono,uno,9.0,...,NaN,NaN,NaN,NaN,43,mujer_cis,no,1,semi-senior,2511178.00
1,buenos_aires,full-time,tercerizado_(trabajo_a_través_de_consultora_o_...,2140000.00,2140000.00,1160,no,no_recibo_bono,uno,5.0,...,NaN,NaN,NaN,NaN,59,mujer_cis,sí,1,senior,2140000.00
2,ciudad_autónoma_de_buenos_aires,full-time,staff_(planta_permanente),3000000.00,310000.00,NaN,3+_sueldos,performance_de_la_compañía,no,0.0,...,NaN,NaN,NaN,NaN,39,hombre_cis,sí,1,semi-senior,3000000.00
3,mendoza,full-time,contractor,4000000.00,4000000.00,1185,no,no_recibo_bono,no,0.0,...,"asincrónicos,_y_sin_plataformas._ejercicios_de...","más_de_8_horas,_sin_problemas","aunque_me_interese,_no_quiero_invertir_mucho_t...",terminar_encuesta,37,hombre_cis,sí,1,senior,4000000.00
4,buenos_aires,full-time,staff_(planta_permanente),1300000.00,1000000.00,NaN,de_uno_a_tres_sueldos,mix_de_las_anteriores,no,0.0,...,NaN,NaN,NaN,NaN,35,hombre_cis,sí,1,senior,1300000.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3743,buenos_aires,part-time,staff_(planta_permanente),4500000.00,4250000.00,NaN,un_sueldo,performance_individual,uno,5.0,...,NaN,NaN,NaN,NaN,27,hombre_cis,no,0,senior,4500000.00
3744,buenos_aires,full-time,tercerizado_(trabajo_a_través_de_consultora_o_...,1400000.00,1200000.00,NaN,no,no_recibo_bono,uno,5.0,...,NaN,NaN,NaN,NaN,25,hombre_cis,sí,0,semi-senior,1400000.00
3745,ciudad_autónoma_de_buenos_aires,full-time,staff_(planta_permanente),3700000.00,3200000.00,NaN,no,no_recibo_bono,dos,16.0,...,NaN,NaN,NaN,NaN,43,hombre_cis,sí,0,senior,3700000.00
3746,ciudad_autónoma_de_buenos_aires,full-time,staff_(planta_permanente),3200000.00,2567000.00,NaN,un_sueldo,mix_de_las_anteriores,tres,25.0,...,NaN,NaN,NaN,NaN,24,hombre_cis,sí,0,semi-senior,3200000.00
3747,santa_fe,full-time,participación_societaria_en_una_cooperativa,1310771.18,1117423.86,NaN,de_uno_a_tres_sueldos,votado_por_decisión_colectiva,uno,21.0,...,"asincrónicos,_y_sin_plataformas._ejercicios_de...",hasta_2_horas,"si_me_interesa_la_empresa,_invierto_todo_el_ti...",terminar_encuesta,33,hombre_cis,no,0,semi-senior,1310771.18

In [22]:
df['contas_con_beneficios_adicionales'].value_counts().nlargest(5).index

Index(['Otros', 'ninguna_de_las_anteriores', 'horarios_flexibles',
       'horarios_flexibles,_vacaciones_flexibles_(adicionales_a_las_reglamentarias)'],
      dtype='object', name='contas_con_beneficios_adicionales')

In [23]:
df.nunique()

donde_estas_trabajando                                                                             24
dedicacion                                                                                          2
tipo_de_contrato                                                                                    5
ultimo_salario_mensual_o_retiro_bruto_en_pesos_argentinos                                        1542
ultimo_salario_mensual_o_retiro_neto_en_pesos_argentinos                                         1463
si_tu_sueldo_esta_dolarizado_cual_fue_el_ultimo_valor_del_dolar_que_tomaron                       216
recibis_algun_tipo_de_bono                                                                          5
a_que_esta_atado_el_bono                                                                          111
tuviste_actualizaciones_de_tus_ingresos_laborales_durante_el_ultimo_semestre                        5
de_que_fue_el_ajuste_total_acumulado                                                              201
en_que_mes_fue_el_ultimo_ajuste                                                                     8
como_consideras_que_estan_tus_ingresos_laborales_comparados_con_el_semestre_anterior                4
contas_con_beneficios_adicionales                                                                   4
que_tan_conforme_estas_con_tus_ingresos_laborales                                                   4
estas_buscando_trabajo                                                                              3
trabajo_de                                                                                         58
anos_de_experiencia                                                                                43
antiguedad_en_la_empresa_actual                                                                    35
anos_en_el_puesto_actual                                                                           29
cuantas_personas_tenes_a_cargo                                                                     44
plataformas_que_utilizas_en_tu_puesto_actual                                                      968
lenguajes_de_programacion_o_tecnologias_que_utilices_en_tu_puesto_actual                         1059
frameworksherramientas_y_librerias_que_utilices_en_tu_puesto_actual                               929
bases_de_datos                                                                                    859
qa_testing                                                                                        428
cantidad_de_personas_en_tu_organizacion                                                            11
modalidad_de_trabajo                                                                                3
si_trabajas_bajo_un_esquema_hibrido_cuantos_dias_a_la_semana_vas_a_la_oficina                       6
en_los_ultimos_6_mesesse_aplico_alguna_politica_de_ajustes_salariales                            1147
en_los_ultimos_6_meseshubo_reduccion_de_personal                                                    3
la_recomendas_como_un_buen_lugar_para_trabajar                                                     11
que_tanto_estas_usando_copilotchatgpt_u_otras_herramientas_de_ia_para_tu_trabajo                    6
vibe_coding                                                                                         3
salir_o_seguir_contestando                                                                          4
carrera                                                                                           124
institucion_educativa                                                                              46
salir_o_seguir_contestando_sobre_las_guardias                                                       3
cual_es_la_cantidad_maxima_de_entrevistas_que_consideras_aceptable_en_un_proceso_de_seleccion       4
cual_es_la_combinacion_de_entrevistas_que_consideras_mejor_en_tu_experiencia_como_candidatoa       55
desafios_tecnicoscomo_los_preferiselegi_todas_las_opciones_que_consideres                          43
cuantas_horas_te_parecen_correctas_dedicarle_a_un_desafio_tecnico_asincronico                       6
cual_de_las_siguientes_frases_representa_mejor_tu_opinion_acerca_de_los_procesos_de_seleccion       4
salir_o_seguir_contestando_sobre_las_guardias1                                                      3
tengo_edad                                                                                         54
genero                                                                                              8
habias_respondido_nuestra_encuesta_en_ediciones_anteriores                                          2
sueldo_dolarizado                                                                                   2
seniority                                                                                           3
_sal                                                                                             1542
dtype: int64

In [24]:
df['recibis_algun_tipo_de_bono'].value_counts().head(5)

recibis_algun_tipo_de_bono
no                       2183
un_sueldo                 529
menos_de_un_sueldo        473
de_uno_a_tres_sueldos     472
3+_sueldos                 91
Name: count, dtype: int64

In [25]:
df['tuviste_actualizaciones_de_tus_ingresos_laborales_durante_el_ultimo_semestre'].value_counts().head(5)

tuviste_actualizaciones_de_tus_ingresos_laborales_durante_el_ultimo_semestre
uno            1288
dos            1032
no              999
tres            219
más_de_tres     210
Name: count, dtype: int64

In [26]:
df['tuviste_actualizaciones_de_tus_ingresos_laborales_durante_el_ultimo_semestre'] = df['tuviste_actualizaciones_de_tus_ingresos_laborales_durante_el_ultimo_semestre'].where(df['tuviste_actualizaciones_de_tus_ingresos_laborales_durante_el_ultimo_semestre'] == 'no', 'si')

In [27]:
df['tuviste_actualizaciones_de_tus_ingresos_laborales_durante_el_ultimo_semestre'] = np.where(df['tuviste_actualizaciones_de_tus_ingresos_laborales_durante_el_ultimo_semestre'] == 'no', 0, 1)

In [28]:
df['tuviste_actualizaciones_de_tus_ingresos_laborales_durante_el_ultimo_semestre'].value_counts().head(5)

tuviste_actualizaciones_de_tus_ingresos_laborales_durante_el_ultimo_semestre
1    2749
0     999
Name: count, dtype: int64

In [29]:
df['estas_buscando_trabajo'].value_counts().head(5)

estas_buscando_trabajo
no,_pero_escucho_ofertas.          2467
sí,_estoy_buscando_activamente.     762
no,_estoy_muy_conforme.             519
Name: count, dtype: int64

In [30]:
df['estas_buscando_trabajo'] = np.where(df['estas_buscando_trabajo'] == 'sí,_estoy_buscando_activamente.', 1, 0)

In [31]:
df['estas_buscando_trabajo'].value_counts().head(5)

estas_buscando_trabajo
0    2986
1     762
Name: count, dtype: int64

In [32]:
df['recibis_algun_tipo_de_bono'] = np.where(df['recibis_algun_tipo_de_bono'] == 'no', 0, 1)

In [33]:
df['trabajo_de'].value_counts().head(8)

trabajo_de
developer                    1301
sysadmin_/_devops_/_sre       419
manager_/_director            343
technical_leader              282
bi_analyst_/_data_analyst     198
qa_/_tester                   188
data_engineer                 110
data_scientist                 87
Name: count, dtype: int64

Elimino el puesto porque todos suman mucho, aunque deje 6 variables me queda 'otros' con gran cantidad

In [34]:
# 1. Encontramos las 3 categorías más repetidas en la columna
top_3_trabajos = df['trabajo_de'].value_counts().nlargest(3).index

# 2. Mantenemos el valor si está en ese top 3; si no, le ponemos 'otro'
df['trabajo_de'] = df['trabajo_de'].where(df['trabajo_de'].isin(top_3_trabajos), 'otro')

In [35]:
df['trabajo_de'].value_counts().head(8)

trabajo_de
otro                       1685
developer                  1301
sysadmin_/_devops_/_sre     419
manager_/_director          343
Name: count, dtype: int64

In [36]:
df=df.drop(columns=['trabajo_de','contas_con_beneficios_adicionales'])

In [37]:
df.nunique()

donde_estas_trabajando                                                                             24
dedicacion                                                                                          2
tipo_de_contrato                                                                                    5
ultimo_salario_mensual_o_retiro_bruto_en_pesos_argentinos                                        1542
ultimo_salario_mensual_o_retiro_neto_en_pesos_argentinos                                         1463
si_tu_sueldo_esta_dolarizado_cual_fue_el_ultimo_valor_del_dolar_que_tomaron                       216
recibis_algun_tipo_de_bono                                                                          2
a_que_esta_atado_el_bono                                                                          111
tuviste_actualizaciones_de_tus_ingresos_laborales_durante_el_ultimo_semestre                        2
de_que_fue_el_ajuste_total_acumulado                                                              201
en_que_mes_fue_el_ultimo_ajuste                                                                     8
como_consideras_que_estan_tus_ingresos_laborales_comparados_con_el_semestre_anterior                4
que_tan_conforme_estas_con_tus_ingresos_laborales                                                   4
estas_buscando_trabajo                                                                              2
anos_de_experiencia                                                                                43
antiguedad_en_la_empresa_actual                                                                    35
anos_en_el_puesto_actual                                                                           29
cuantas_personas_tenes_a_cargo                                                                     44
plataformas_que_utilizas_en_tu_puesto_actual                                                      968
lenguajes_de_programacion_o_tecnologias_que_utilices_en_tu_puesto_actual                         1059
frameworksherramientas_y_librerias_que_utilices_en_tu_puesto_actual                               929
bases_de_datos                                                                                    859
qa_testing                                                                                        428
cantidad_de_personas_en_tu_organizacion                                                            11
modalidad_de_trabajo                                                                                3
si_trabajas_bajo_un_esquema_hibrido_cuantos_dias_a_la_semana_vas_a_la_oficina                       6
en_los_ultimos_6_mesesse_aplico_alguna_politica_de_ajustes_salariales                            1147
en_los_ultimos_6_meseshubo_reduccion_de_personal                                                    3
la_recomendas_como_un_buen_lugar_para_trabajar                                                     11
que_tanto_estas_usando_copilotchatgpt_u_otras_herramientas_de_ia_para_tu_trabajo                    6
vibe_coding                                                                                         3
salir_o_seguir_contestando                                                                          4
carrera                                                                                           124
institucion_educativa                                                                              46
salir_o_seguir_contestando_sobre_las_guardias                                                       3
cual_es_la_cantidad_maxima_de_entrevistas_que_consideras_aceptable_en_un_proceso_de_seleccion       4
cual_es_la_combinacion_de_entrevistas_que_consideras_mejor_en_tu_experiencia_como_candidatoa       55
desafios_tecnicoscomo_los_preferiselegi_todas_las_opciones_que_consideres                          43
cuantas_horas_te_parecen_correctas_dedicarle_a_un_desafio_tecnico_asincronico                       6
cual_de_las_siguientes_frases_representa_mejor_tu_opinion_acerca_de_los_procesos_de_seleccion       4
salir_o_seguir_contestando_sobre_las_guardias1                                                      3
tengo_edad                                                                                         54
genero                                                                                              8
habias_respondido_nuestra_encuesta_en_ediciones_anteriores                                          2
sueldo_dolarizado                                                                                   2
seniority                                                                                           3
_sal                                                                                             1542
dtype: int64

In [38]:
df['cuantas_personas_tenes_a_cargo'].value_counts().head(44)

cuantas_personas_tenes_a_cargo
0      2653
2       191
1       181
3       122
5       110
4       103
10       57
6        51
8        40
15       33
7        27
20       25
12       22
9        21
11       14
14       11
25       10
16        9
30        8
40        8
13        6
60        4
50        4
18        4
22        4
80        3
26        3
100       2
190       2
45        2
200       2
120       2
35        2
17        2
65        1
21        1
27        1
66        1
70        1
24        1
38        1
19        1
28        1
55        1
Name: count, dtype: int64

In [39]:
df['cuantas_personas_tenes_a_cargo'] = np.where(df['cuantas_personas_tenes_a_cargo'] > 0, 1,0)

In [40]:
df['cuantas_personas_tenes_a_cargo'].value_counts().head(44)

cuantas_personas_tenes_a_cargo
0    2653
1    1095
Name: count, dtype: int64

In [41]:
df=df.drop(columns='cantidad_de_personas_en_tu_organizacion')

In [42]:
df

,donde_estas_trabajando,dedicacion,tipo_de_contrato,ultimo_salario_mensual_o_retiro_bruto_en_pesos_argentinos,ultimo_salario_mensual_o_retiro_neto_en_pesos_argentinos,si_tu_sueldo_esta_dolarizado_cual_fue_el_ultimo_valor_del_dolar_que_tomaron,recibis_algun_tipo_de_bono,a_que_esta_atado_el_bono,tuviste_actualizaciones_de_tus_ingresos_laborales_durante_el_ultimo_semestre,de_que_fue_el_ajuste_total_acumulado,...,desafios_tecnicoscomo_los_preferiselegi_todas_las_opciones_que_consideres,cuantas_horas_te_parecen_correctas_dedicarle_a_un_desafio_tecnico_asincronico,cual_de_las_siguientes_frases_representa_mejor_tu_opinion_acerca_de_los_procesos_de_seleccion,salir_o_seguir_contestando_sobre_las_guardias1,tengo_edad,genero,habias_respondido_nuestra_encuesta_en_ediciones_anteriores,sueldo_dolarizado,seniority,_sal
0,ciudad_autónoma_de_buenos_aires,full-time,staff_(planta_permanente),2511178.00,2085000.00,dólar_oficial_al_día_de_oago,0,no_recibo_bono,1,9.0,...,NaN,NaN,NaN,NaN,43,mujer_cis,no,1,semi-senior,2511178.00
1,buenos_aires,full-time,tercerizado_(trabajo_a_través_de_consultora_o_...,2140000.00,2140000.00,1160,0,no_recibo_bono,1,5.0,...,NaN,NaN,NaN,NaN,59,mujer_cis,sí,1,senior,2140000.00
2,ciudad_autónoma_de_buenos_aires,full-time,staff_(planta_permanente),3000000.00,310000.00,NaN,1,performance_de_la_compañía,0,0.0,...,NaN,NaN,NaN,NaN,39,hombre_cis,sí,1,semi-senior,3000000.00
3,mendoza,full-time,contractor,4000000.00,4000000.00,1185,0,no_recibo_bono,0,0.0,...,"asincrónicos,_y_sin_plataformas._ejercicios_de...","más_de_8_horas,_sin_problemas","aunque_me_interese,_no_quiero_invertir_mucho_t...",terminar_encuesta,37,hombre_cis,sí,1,senior,4000000.00
4,buenos_aires,full-time,staff_(planta_permanente),1300000.00,1000000.00,NaN,1,mix_de_las_anteriores,0,0.0,...,NaN,NaN,NaN,NaN,35,hombre_cis,sí,1,senior,1300000.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3743,buenos_aires,part-time,staff_(planta_permanente),4500000.00,4250000.00,NaN,1,performance_individual,1,5.0,...,NaN,NaN,NaN,NaN,27,hombre_cis,no,0,senior,4500000.00
3744,buenos_aires,full-time,tercerizado_(trabajo_a_través_de_consultora_o_...,1400000.00,1200000.00,NaN,0,no_recibo_bono,1,5.0,...,NaN,NaN,NaN,NaN,25,hombre_cis,sí,0,semi-senior,1400000.00
3745,ciudad_autónoma_de_buenos_aires,full-time,staff_(planta_permanente),3700000.00,3200000.00,NaN,0,no_recibo_bono,1,16.0,...,NaN,NaN,NaN,NaN,43,hombre_cis,sí,0,senior,3700000.00
3746,ciudad_autónoma_de_buenos_aires,full-time,staff_(planta_permanente),3200000.00,2567000.00,NaN,1,mix_de_las_anteriores,1,25.0,...,NaN,NaN,NaN,NaN,24,hombre_cis,sí,0,semi-senior,3200000.00
3747,santa_fe,full-time,participación_societaria_en_una_cooperativa,1310771.18,1117423.86,NaN,1,votado_por_decisión_colectiva,1,21.0,...,"asincrónicos,_y_sin_plataformas._ejercicios_de...",hasta_2_horas,"si_me_interesa_la_empresa,_invierto_todo_el_ti...",terminar_encuesta,33,hombre_cis,no,0,semi-senior,1310771.18

In [43]:
df.nunique()

donde_estas_trabajando                                                                             24
dedicacion                                                                                          2
tipo_de_contrato                                                                                    5
ultimo_salario_mensual_o_retiro_bruto_en_pesos_argentinos                                        1542
ultimo_salario_mensual_o_retiro_neto_en_pesos_argentinos                                         1463
si_tu_sueldo_esta_dolarizado_cual_fue_el_ultimo_valor_del_dolar_que_tomaron                       216
recibis_algun_tipo_de_bono                                                                          2
a_que_esta_atado_el_bono                                                                          111
tuviste_actualizaciones_de_tus_ingresos_laborales_durante_el_ultimo_semestre                        2
de_que_fue_el_ajuste_total_acumulado                                                              201
en_que_mes_fue_el_ultimo_ajuste                                                                     8
como_consideras_que_estan_tus_ingresos_laborales_comparados_con_el_semestre_anterior                4
que_tan_conforme_estas_con_tus_ingresos_laborales                                                   4
estas_buscando_trabajo                                                                              2
anos_de_experiencia                                                                                43
antiguedad_en_la_empresa_actual                                                                    35
anos_en_el_puesto_actual                                                                           29
cuantas_personas_tenes_a_cargo                                                                      2
plataformas_que_utilizas_en_tu_puesto_actual                                                      968
lenguajes_de_programacion_o_tecnologias_que_utilices_en_tu_puesto_actual                         1059
frameworksherramientas_y_librerias_que_utilices_en_tu_puesto_actual                               929
bases_de_datos                                                                                    859
qa_testing                                                                                        428
modalidad_de_trabajo                                                                                3
si_trabajas_bajo_un_esquema_hibrido_cuantos_dias_a_la_semana_vas_a_la_oficina                       6
en_los_ultimos_6_mesesse_aplico_alguna_politica_de_ajustes_salariales                            1147
en_los_ultimos_6_meseshubo_reduccion_de_personal                                                    3
la_recomendas_como_un_buen_lugar_para_trabajar                                                     11
que_tanto_estas_usando_copilotchatgpt_u_otras_herramientas_de_ia_para_tu_trabajo                    6
vibe_coding                                                                                         3
salir_o_seguir_contestando                                                                          4
carrera                                                                                           124
institucion_educativa                                                                              46
salir_o_seguir_contestando_sobre_las_guardias                                                       3
cual_es_la_cantidad_maxima_de_entrevistas_que_consideras_aceptable_en_un_proceso_de_seleccion       4
cual_es_la_combinacion_de_entrevistas_que_consideras_mejor_en_tu_experiencia_como_candidatoa       55
desafios_tecnicoscomo_los_preferiselegi_todas_las_opciones_que_consideres                          43
cuantas_horas_te_parecen_correctas_dedicarle_a_un_desafio_tecnico_asincronico                       6
cual_de_las_siguientes_frases_representa_mejor_tu_opinion_acerca_de_los_procesos_de_seleccion       4
salir_o_seguir_contestando_sobre_las_guardias1                                                      3
tengo_edad                                                                                         54
genero                                                                                              8
habias_respondido_nuestra_encuesta_en_ediciones_anteriores                                          2
sueldo_dolarizado                                                                                   2
seniority                                                                                           3
_sal                                                                                             1542
dtype: int64

In [44]:
# Reemplaza 'sueldo' por el nombre exacto de tu columna
df = df[df['_sal'] >= 800000]

In [45]:
df = df[df['tengo_edad'] < 90]

In [46]:
# Esto convierte tu recorte en un DataFrame independiente
df = df.copy()

# Ahora tu código correrá perfectamente y sin advertencias:
df['anos_en_el_puesto_actual'] = df['anos_en_el_puesto_actual'].replace({2016: 10, 2023: 3})

In [47]:
categorias_filtro=['donde_estas_trabajando','dedicacion','recibis_algun_tipo_de_bono','tuviste_actualizaciones_de_tus_ingresos_laborales_durante_el_ultimo_semestre',
'estas_buscando_trabajo',
'anos_de_experiencia',
'antiguedad_en_la_empresa_actual',
'anos_en_el_puesto_actual', 
'cuantas_personas_tenes_a_cargo',
'modalidad_de_trabajo',
'tengo_edad',
'genero',
'sueldo_dolarizado',
'seniority','_sal']

In [48]:
df=df[categorias_filtro].copy()

In [64]:
global_sal=df._sal.mean()
for c in categorias_filtro:
    df_group=df.groupby(c)._sal.agg(['mean','count'])
    df_group['diff']=df_group['mean']-global_sal
    display(df_group)
    print()
    print()

                                         mean  count          diff
donde_estas_trabajando
buenos_aires                     3.392186e+06    754  1.399222e+04
catamarca                        4.813158e+06      1  1.434964e+06
chaco                            2.318247e+06     28 -1.059947e+06
chubut                           2.595035e+06     17 -7.831592e+05
ciudad_autónoma_de_buenos_aires  3.564122e+06   1837  1.859278e+05
corrientes                       2.769194e+06     18 -6.090000e+05
córdoba                          3.150475e+06    325 -2.277193e+05
entre_ríos                       2.784669e+06     60 -5.935250e+05
formosa                          1.600000e+06      1 -1.778194e+06
jujuy                            3.607199e+06     19  2.290048e+05
la_pampa                         4.783767e+06      9  1.405573e+06
la_rioja                         2.559450e+06     12 -8.187439e+05
mendoza                          2.943426e+06    119 -4.347685e+05
misiones                         2.452364e+06     32 -9.258305e+05
neuquén                          2.969967e+06     23 -4.082267e+05
río_negro                        3.206925e+06     37 -1.712689e+05
salta                            2.410904e+06     27 -9.672903e+05
san_juan                         2.815626e+06     11 -5.625685e+05
san_luis                         2.922970e+06     15 -4.552243e+05
santa_cruz                       2.936395e+06      5 -4.417988e+05
santa_fe                         3.293302e+06    270 -8.489169e+04
santiago_del_estero              1.922646e+06      9 -1.455548e+06
tierra_del_fuego                 3.188381e+06      6 -1.898130e+05
tucumán                          2.719333e+06     30 -6.588612e+05

                    mean  count          diff
dedicacion
full-time   3.422648e+06   3543  4.445377e+04
part-time   2.087213e+06    122 -1.290981e+06

                                    mean  count           diff
recibis_algun_tipo_de_bono
0                           3.084656e+06   2113 -293538.634673
1                           3.777838e+06   1552  399643.772593

,mean,count,diff
tuviste_actualizaciones_de_tus_ingresos_laborales_durante_el_ultimo_semestre,,,
0,3.809395e+06,966,431200.695413
1,3.223863e+06,2699,-154331.186280

                                mean  count           diff
estas_buscando_trabajo
0                       3.568380e+06   2938  190185.752591
1                       2.609603e+06    727 -768591.115698

                             mean  count          diff
anos_de_experiencia
0                    1.854409e+06     50 -1.523785e+06
1                    1.931904e+06    125 -1.446290e+06
2                    2.001338e+06    248 -1.376857e+06
3                    2.317727e+06    449 -1.060467e+06
4                    2.644258e+06    387 -7.339362e+05
5                    3.181287e+06    354 -1.969076e+05
6                    3.367755e+06    216 -1.043939e+04
7                    3.776369e+06    173  3.981751e+05
8                    3.714052e+06    138  3.358580e+05
9                    4.051065e+06     73  6.728705e+05
10                   3.796075e+06    242  4.178805e+05
11                   4.069213e+06     50  6.910193e+05
12                   4.236381e+06     95  8.581867e+05
13                   3.888402e+06     49  5.102078e+05
14                   4.742074e+06     49  1.363880e+06
15                   4.170162e+06    197  7.919676e+05
16                   4.323018e+06     43  9.448239e+05
17                   4.590570e+06     60  1.212375e+06
18                   4.772940e+06     90  1.394746e+06
19                   4.303574e+06     33  9.253799e+05
20                   4.155181e+06    190  7.769866e+05
21                   5.538005e+06     14  2.159810e+06
22                   4.601603e+06     31  1.223409e+06
23                   3.439841e+06     17  6.164711e+04
24                   4.140715e+06     15  7.625208e+05
25                   4.604995e+06    106  1.226801e+06
26                   5.989264e+06     14  2.611070e+06
27                   5.397323e+06     18  2.019129e+06
28                   5.132622e+06     14  1.754428e+06
29                   5.810250e+06      4  2.432056e+06
30                   3.734963e+06     65  3.567688e+05
31                   4.602070e+06      7  1.223876e+06
32                   3.321560e+06      7 -5.663375e+04
33                   5.366667e+06      3  1.988472e+06
34                   4.150000e+06      2  7.718058e+05
35                   4.201056e+06     15  8.228621e+05
37                   3.000000e+06      1 -3.781942e+05
38                   5.466667e+06      6  2.088472e+06
39                   4.247816e+06      2  8.696218e+05
40                   3.630341e+06      9  2.521466e+05
42                   3.123667e+06      3 -2.545275e+05
46                   3.000000e+06      1 -3.781942e+05

                                         mean  count          diff
antiguedad_en_la_empresa_actual
0                                3.391684e+06    595  1.349006e+04
1                                3.010599e+06    518 -3.675953e+05
2                                2.960474e+06    549 -4.177205e+05
3                                3.239856e+06    632 -1.383378e+05
4                                3.497587e+06    373  1.193925e+05
5                                3.948602e+06    235  5.704077e+05
6                                4.126691e+06    142  7.484967e+05
7                                3.721878e+06     87  3.436833e+05
8                                3.694484e+06     64  3.162899e+05
9                                4.030637e+06     43  6.524432e+05
10                               3.701112e+06     87  3.229178e+05
11                               3.879463e+06     34  5.012689e+05
12                               3.341350e+06     50 -3.684418e+04
13                               3.935927e+06     39  5.577333e+05
14                               3.605158e+06     29  2.269636e+05
15                               3.582318e+06     44  2.041239e+05
16                               4.278611e+06     17  9.004164e+05
17                               4.476213e+06     12  1.098019e+06
18                               3.252745e+06     24 -1.254490e+05
19                               4.654514e+06      8  1.276320e+06
20                               3.737967e+06     30  3.597725e+05
21                               4.273914e+06      7  8.957194e+05
22                               3.713861e+06      5  3.356672e+05
23                               5.069377e+06      4  1.691183e+06
25                               3.062618e+06     10 -3.155765e+05
26                               3.884850e+06      2  5.066558e+05
27                               4.451852e+06      3  1.073657e+06
28                               3.396448e+06      9  1.825426e+04
30                               2.427117e+06      5 -9.510770e+05
32                               1.300000e+06      1 -2.078194e+06
35                               2.250000e+06      3 -1.128194e+06
39                               7.000000e+06      1  3.621806e+06
40                               3.000000e+06      1 -3.781942e+05
42                               3.385500e+06      2  7.305819e+03

                                  mean  count          diff
anos_en_el_puesto_actual
0                         3.372704e+06    513 -5.490059e+03
1                         3.031130e+06    638 -3.470641e+05
2                         3.250593e+06    692 -1.276015e+05
3                         3.349816e+06    673 -2.837826e+04
4                         3.488730e+06    353  1.105354e+05
5                         3.775727e+06    263  3.975330e+05
6                         3.969779e+06    124  5.915846e+05
7                         4.060616e+06     81  6.824221e+05
8                         3.313483e+06     67 -6.471077e+04
9                         3.696671e+06     26  3.184771e+05
10                        3.989033e+06     79  6.108387e+05
11                        3.418477e+06      9  4.028304e+04
12                        3.313459e+06     28 -6.473503e+04
13                        2.918854e+06     15 -4.593404e+05
14                        3.319097e+06      8 -5.909718e+04
15                        3.578312e+06     39  2.001178e+05
16                        3.143329e+06      8 -2.348656e+05
17                        4.875000e+06      4  1.496806e+06
18                        4.140495e+06     10  7.623009e+05
19                        2.373333e+06      3 -1.004861e+06
20                        2.845252e+06     15 -5.329421e+05
21                        3.643942e+06      2  2.657478e+05
25                        3.569444e+06      9  1.912503e+05
28                        4.500000e+06      1  1.121806e+06
30                        5.920197e+06      2  2.542003e+06
33                        2.500000e+06      1 -8.781942e+05
35                        3.350000e+06      2 -2.819418e+04

                                        mean  count           diff
cuantas_personas_tenes_a_cargo
0                               3.090412e+06   2584 -287782.127735
1                               4.066103e+06   1081  687908.434845

                                       mean  count           diff
modalidad_de_trabajo
100%_presencial                2.421867e+06    269 -956327.161403
100%_remoto                    3.507072e+06   1817  128877.529543
híbrido_(presencial_y_remoto)  3.392812e+06   1579   14617.818390

                    mean  count          diff
tengo_edad
19          2.000000e+06      1 -1.378194e+06
20          1.560000e+06      5 -1.818194e+06
21          2.164746e+06      3 -1.213449e+06
22          1.783121e+06     24 -1.595074e+06
23          1.916298e+06     37 -1.461897e+06
24          2.150280e+06     91 -1.227914e+06
25          2.442040e+06     83 -9.361542e+05
26          2.360013e+06     97 -1.018181e+06
27          2.725943e+06    126 -6.522516e+05
28          2.827345e+06    171 -5.508487e+05
29          2.784956e+06    191 -5.932379e+05
30          3.019052e+06    190 -3.591420e+05
31          2.982418e+06    145 -3.957763e+05
32          3.379956e+06    173  1.762142e+03
33          3.167036e+06    183 -2.111584e+05
34          3.304989e+06    183 -7.320499e+04
35          3.461553e+06    185  8.335845e+04
36          3.458421e+06    161  8.022668e+04
37          3.521021e+06    150  1.428271e+05
38          3.924315e+06    145  5.461206e+05
39          3.852402e+06    127  4.742081e+05
40          4.073832e+06    147  6.956381e+05
41          3.887029e+06    136  5.088345e+05
42          3.716695e+06    106  3.385008e+05
43          3.800400e+06    101  4.222054e+05
44          3.730566e+06     77  3.523713e+05
45          4.195950e+06     85  8.177560e+05
46          4.135236e+06     73  7.570414e+05
47          4.436726e+06     75  1.058531e+06
48          3.862762e+06     67  4.845675e+05
49          3.819268e+06     42  4.410740e+05
50          4.267226e+06     63  8.890322e+05
51          4.206008e+06     34  8.278135e+05
52          4.316722e+06     34  9.385282e+05
53          3.828554e+06     23  4.503596e+05
54          3.875300e+06      9  4.971058e+05
55          3.463553e+06     25  8.535922e+04
56          4.034125e+06     16  6.559308e+05
57          3.689016e+06     17  3.108213e+05
58          3.578152e+06      9  1.999577e+05
59          3.206500e+06     10 -1.716942e+05
60          3.475332e+06     15  9.713785e+04
61          3.199556e+06      9 -1.786386e+05
62          4.626667e+06      6  1.248472e+06
63          1.850000e+06      1 -1.528194e+06
64          2.700000e+06      4 -6.781942e+05
65          1.650667e+06      3 -1.727528e+06
66          3.160000e+06      2 -2.181942e+05
68          3.900000e+06      1  5.218058e+05
72          2.500000e+06      1 -8.781942e+05
73          2.155000e+06      1 -1.223194e+06
74          1.125000e+06      2 -2.253194e+06

                           mean  count          diff
genero
agénero            2.120416e+06      2 -1.257779e+06
fluido             1.538090e+06      1 -1.840104e+06
hombre_cis         3.540119e+06   2886  1.619250e+05
mujer_cis          2.741775e+06    719 -6.364192e+05
no_binarie         2.122934e+06     10 -1.255260e+06
prefiero_no_decir  3.704443e+06     35  3.262484e+05
queer              3.143963e+06      6 -2.342312e+05
trans              2.905657e+06      6 -4.725368e+05

                           mean  count           diff
sueldo_dolarizado
0                  3.015978e+06   2409 -362216.374254
1                  4.072923e+06   1256  694728.698709

                     mean  count          diff
seniority
junior       1.963452e+06    423 -1.414742e+06
semi-senior  2.680809e+06   1190 -6.973852e+05
senior       4.074259e+06   2052  6.960645e+05

                    mean  count          diff
_sal
800000.00      800000.00      6 -2.578194e+06
810000.00      810000.00      1 -2.568194e+06
823761.54      823761.54      1 -2.554433e+06
830000.00      830000.00      1 -2.548194e+06
832994.31      832994.31      1 -2.545200e+06
...                  ...    ...           ...
13500000.00  13500000.00      1  1.012181e+07
14000000.00  14000000.00      3  1.062181e+07
14160000.00  14160000.00      1  1.078181e+07
15000000.00  15000000.00      1  1.162181e+07
15675000.00  15675000.00      1  1.229681e+07

[1484 rows x 3 columns]

In [50]:
df_completo = pd.get_dummies(df)

In [51]:
from sklearn.model_selection import train_test_split

In [52]:
df_train_val,df_test=train_test_split(df_completo,test_size=0.2,random_state=1)

In [53]:
df_train,df_val=train_test_split(df_train_val, test_size=0.25,random_state=1)

In [54]:
len(df_train),len( df_test),len( df_val)

(2199, 733, 733)

In [55]:
df_train=df_train.reset_index(drop=True)
df_val=df_val.reset_index(drop=True)
df_test=df_test.reset_index(drop=True)

In [56]:
y_train=df_train['_sal']
y_val=df_val['_sal']
y_test=df_test['_sal']

In [57]:
del df_train['_sal']
del df_val['_sal']
del df_test['_sal']

In [58]:
y_train.mean()

np.float64(3371024.676325603)

In [59]:
y_val.mean()

np.float64(3312905.58840382)

In [60]:
y_test.mean()

np.float64(3464991.285729878)

In [61]:
from sklearn.metrics import mutual_info_score

In [62]:
def mutual_sal_score(series):
    return mutual_info_score(series, df_train_val._sal)

In [63]:
from sklearn.linear_model import LinearRegression

# Cambiamos el modelo
model = LinearRegression()
model.fit(df_train, y_train)

LinearRegression()

In [65]:
y_pred= model.predict(df_val)

In [66]:
(y_pred == y_val).value_counts()

_sal
False    733
Name: count, dtype: int64

In [67]:
from sklearn.metrics import mean_absolute_error, r2_score
import numpy as np

# Calculamos el error promedio en pesos
# (Nota: asumo que y_pred lo generaste con X_val, así que lo comparamos con y_val)
# Si tu y_pred era sobre X_train, cambia y_val por y_train aquí abajo:
mae = mean_absolute_error(y_val, y_pred)

# Calculamos el R2 (Qué porcentaje de los sueldos logra explicar tu modelo)
# El máximo perfecto es 1.0
r2 = r2_score(y_val, y_pred)

print(f"Error Absoluto Medio (MAE): El modelo se equivoca en promedio por ${mae:,.2f} pesos.")
print(f"Puntaje R2: {r2:.2f}")

Error Absoluto Medio (MAE): El modelo se equivoca en promedio por $1,143,015.77 pesos.
Puntaje R2: 0.34

In [68]:
import pandas as pd

# Armamos un dataframe rápido para comparar mano a mano
comparacion = pd.DataFrame({
    'Sueldo Real': y_val.values[:10], # Cambia y_val por y_train si es necesario
    'Sueldo Predicho': y_pred[:10].round(0)
})

# Agregamos una columna para ver la diferencia de plata
comparacion['Diferencia'] = comparacion['Sueldo Real'] - comparacion['Sueldo Predicho']

print(comparacion)

   Sueldo Real  Sueldo Predicho  Diferencia
0    2200000.0        3832055.0  -1632055.0
1    5498116.0        3706345.0   1791771.0
2    1200000.0        1794452.0   -594452.0
3    3744000.0        4823358.0  -1079358.0
4    2700000.0        2560242.0    139758.0
5    1308377.0        1877734.0   -569357.0
6    2200000.0        3788448.0  -1588448.0
7    3100000.0        3599364.0   -499364.0
8    3000000.0        3785046.0   -785046.0
9    1650000.0        1256192.0    393808.0

In [69]:

# 1. Transformamos los sueldos a logaritmo (esto "suaviza" la curva de salarios)
y_train_log = np.log1p(y_train)
y_val_log = np.log1p(y_val)

# 2. Entrenamos el mismo modelo, pero ahora intentará adivinar el logaritmo
rf_model_log = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1)
rf_model_log.fit(df_train, y_train_log)

# 3. Hacemos las predicciones (el resultado saldrá en formato logaritmo)
y_pred_log = rf_model_log.predict(df_val)

# 4. Magia: Volvemos a convertir el logaritmo a Pesos Reales usando la exponencial
y_pred_real = np.expm1(y_pred_log)

# 5. Medimos contra los sueldos reales (y_val)
mae_log = mean_absolute_error(y_val, y_pred_real)
r2_log = r2_score(y_val, y_pred_real)

print("-" * 30)
print(f"Error Absoluto Medio (Modelo Logarítmico): ${mae_log:,.2f} pesos.")
print(f"Puntaje R2 (Modelo Logarítmico): {r2_log:.2f}")

# 1. Transformamos los sueldos a logaritmo (esto "suaviza" la curva de salarios)
y_train_log = np.log1p(y_train)
y_val_log = np.log1p(y_val)

# 2. Entrenamos el mismo modelo, pero ahora intentará adivinar el logaritmo
rf_model_log = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1)
rf_model_log.fit(df_train, y_train_log)

# 3. Hacemos las predicciones (el resultado saldrá en formato logaritmo)
y_pred_log = rf_model_log.predict(df_val)

# 4. Magia: Volvemos a convertir el logaritmo a Pesos Reales usando la exponencial
y_pred_real = np.expm1(y_pred_log)

# 5. Medimos contra los sueldos reales (y_val)
mae_log = mean_absolute_error(y_val, y_pred_real)
r2_log = r2_score(y_val, y_pred_real)

print("-" * 30)
print(f"Error Absoluto Medio (Modelo Logarítmico): ${mae_log:,.2f} pesos.")
print(f"Puntaje R2 (Modelo Logarítmico): {r2_log:.2f}")

NameError: name 'RandomForestRegressor' is not defined

In [70]:
import pandas as pd

# Creamos una tabla con la importancia de cada columna
importancias = pd.DataFrame({
    'Variable': df_train.columns,
    'Importancia': rf_model.feature_importances_
})

# Las ordenamos de mayor a menor y mostramos el Top 10
top_variables = importancias.sort_values(by='Importancia', ascending=False).head(10)
print("Las 10 variables que más definen el sueldo son:")
print(top_variables)

NameError: name 'rf_model' is not defined

In [72]:
import xgboost as xgb
import numpy as np
from sklearn.metrics import mean_absolute_error, r2_score

# 1. Transformamos los sueldos a logaritmo (nuestra mejor estrategia)
y_train_log = np.log1p(y_train)
y_val_log = np.log1p(y_val)

# 2. Creamos el modelo XGBoost
# learning_rate es la velocidad a la que aprende de sus errores (0.1 es un buen estándar)
xgb_model = xgb.XGBRegressor(n_estimators=100, learning_rate=0.1, random_state=42, n_jobs=-1)

print("Entrenando el poderoso XGBoost... 🚀")
xgb_model.fit(df_train, y_train_log)

# 3. Hacemos las predicciones y revertimos el logaritmo a plata real
y_pred_xgb_log = xgb_model.predict(df_val)
y_pred_xgb_real = np.expm1(y_pred_xgb_log)

# 4. Medimos contra la realidad
mae_xgb = mean_absolute_error(y_val, y_pred_xgb_real)
r2_xgb = r2_score(y_val, y_pred_xgb_real)

print("-" * 30)
print(f"Error Absoluto Medio (XGBoost): ${mae_xgb:,.2f} pesos.")
print(f"Puntaje R2 (XGBoost): {r2_xgb:.2f}")

Entrenando el poderoso XGBoost... 🚀
------------------------------
Error Absoluto Medio (XGBoost): $1,052,420.41 pesos.
Puntaje R2 (XGBoost): 0.37

In [74]:
import joblib

# 1. Guardamos el modelo XGBoost
joblib.dump(xgb_model, 'modelo_xgb.pkl')

# 2. Guardamos la estructura exacta de las columnas de X_train
joblib.dump(list(df_train.columns), 'columnas.pkl')

print("¡Archivos exportados con éxito!")

¡Archivos exportados con éxito!